### ISSUE TITLE
6.2 Parte -> 2 Se crea la base de datos y la tabla => se configura el archivo db.js

### ISSUE THREAD

**Issue by bguzmanech** [CodeSystem2022/Perricornios-Cuarto-Semestre#352]
Video 3

**Comment by NaSP32** [comment]
La tarea no se puede comenzar a llevar a cabo porque el repositorio de semana 6 Js quedo desordenado. 
Los comandos npm run dev no funcionan
Las carpetas no estan en donde deberian
El index.js contiene errores
