### ISSUE TITLE
8.3 Relacionamos las tareas con el usuario - Se utiliza el md5 para el avatar (video 3)

### ISSUE THREAD

**Issue by Noelia-Ruiz** [CodeSystem2022/Perricornios-Cuarto-Semestre#452]

**Comment by Noelia-Ruiz** [comment]
Juani, te dejo un comentario porque el video es demasiado largo. Tiene prioridad media, hasta jueves podes subirlo tranquilamente así no se atrasan los chicos que siguen! 

PD: No te olvides de adjuntar alguna captura de ejecución a lo que hace en el código (que son bastantes cambios) en la carpeta de PRUEBAS dentro de la materia JavaScript

**Comment by Noelia-Ruiz** [comment]
Juani, buenas noches!! Ya están los dos primeros videos para que puedas hacer tu parte. Acordate que esta issue cierra mas tardar el jueves, ya que los videos son hiper largos.

**Comment by Noelia-Ruiz** [comment]
Juani, tengo personas esperando esta parte del código para poder avanzar. Me comentas si la pudiste hacer, estás en eso o se te complicó algo? Acordate que este tipo de prioridad (media) tiene tiempo de entrega hasta mañana. Buenas noches!

**Comment by asterisko19** [comment]
Hola noe que tal, si lo pude ver, hoy lo subo el problema que tengo es que no puedo ejecutarlo creo que me debe faltar algo

**Comment by Noelia-Ruiz** [comment]
Juani, gracias por responder! Ya sabiendo que estas trabajando las cosas cambian, seguí revisando tranquilo. Mañana continuará Gabriel, no hay problemas! :)

**Comment by Noelia-Ruiz** [comment]
Gabriel, esta es tu nueva issue 💪 resuelve de hoy hasta mañana

**Comment by GabJaJ** [comment]
Tarea recibida Noe, yo me encargo!
