### ISSUE TITLE
8.4 Configuración frontend - inicio y creación de rutas (video 4)

### ISSUE THREAD

**Issue by Noelia-Ruiz** [CodeSystem2022/Perricornios-Cuarto-Semestre#454]

**Comment by Noelia-Ruiz** [comment]
Gabriel! Lo mismo que a Juani, es super extenso este video, les puse prioridad media y tienen hasta el jueves para cargarlo
PD: En la carpeta de PRUEBAS podes adjuntar las capturas de ejecución que correspondan

**Comment by GabJaJ** [comment]
Tarea Recibida!!

Perfecto Noe adjunto capturas de las pruebas ejecutadas!
