### ISSUE TITLE
8.5 Formulario de registro Parte 2 - video 6

### ISSUE THREAD

**Issue by Noelia-Ruiz** [CodeSystem2022/Perricornios-Cuarto-Semestre#456]

**Comment by Noelia-Ruiz** [comment]
Carlos! Lo mismo que a los chicos, el video es super extenso por eso tiene prioridad baja y puede cargarse hasta el sabado.
PD: En la carpeta de PRUEBAS podes adjuntar las capturas de ejecución del código a medida que Daniel va haciendo los cambios. Podes cargar las que vos creas importante.

**Comment by Noelia-Ruiz** [comment]
Juani! Esta es tu nueva issue 💪 hacelo tranquilo, cierra hasta el domingo

**Comment by Noelia-Ruiz** [comment]
Buenas noches, paso a avisar que está todo en orden el proyecto, avisá si podes resolver hasta mañana domingo o no. En caso de que sí, presentá las capturas correspondientes (todo quedó funcionando), en caso de que no, me hago cargo yo para yo poder resolver hasta lunes que es donde ya arranca otra semana y otro scrum.

**Comment by asterisko19** [comment]
Perdón la hora, ahora lo subo

**Comment by Noelia-Ruiz** [comment]
Perfecto, sino mañana me lo reasigno. No te olvides las capturas 🙏
