### ISSUE TITLE
Parte 2 - Botones para modificar, eliminar y damos forma visual (video 3)

### ISSUE THREAD

**Issue by Noelia-Ruiz** [CodeSystem2022/Perricornios-Cuarto-Semestre#462]

**Comment by Noelia-Ruiz** [comment]
Esta issue debió cerrar jueves. Presentarla en el trascurso del día 🙏

**Comment by Noelia-Ruiz** [comment]
Braian esta issue cargala como la tengas nomas, el proyecto venía con fallas. En la semana se revisa

**Comment by bguzmanech** [comment]
Bueno, a la tarde la cargo

**Comment by bguzmanech** [comment]
Listo

**Comment by Noelia-Ruiz** [comment]
Gracias Braian 💪
