### ISSUE TITLE
13.1 Introducción y teoría (Video1)

### ISSUE THREAD

**Issue by NaSP32** [CodeSystem2022/Perricornios-Cuarto-Semestre#642]

**Comment by Noelia-Ruiz** [comment]
Pido este mi Na 💪 termina el streaming y lo cargo

**Comment by NaSP32** [comment]
Perfecto @Noelia-Ruiz te la asigno!

**Comment by Noelia-Ruiz** [comment]
Actividad realizada mi Na :)

**Comment by NaSP32** [comment]
Muchisimas gracias Noe por tu participacion en esta actividad y en todas las demas! Node concluido para vos =) !
Nos leemos en la proxima issue 🥳
